-- ATIVIDADE -- 

-- 1) CRIAR UM DATA BASE COM O NOME EMPRESA
-- 2) CRIAR UMA TABELA CARGO (ID, NOMEDOCARGO, FUNÇÃO)
-- 3) CADASTRAR 4 CARGOS
-- 4) TREINAR O SELECT, DROP, ALTER, UPDATE, DELETE COM ESSA TABELA

-- 5) CRIAR UMA TABELA FUNCIONÁRIO(ID, NOME, SALÁRIO, CARGO_ID)
		-- O CAMPO CARGO ID DEVERÁ SER A FOREIGN KEY QUE FARÁ O RELACIONAMENTO COM A TABELA DE CARGOS

-- 6) CADASTRAR 4 FUNCIONÁRIOS COM SEUS RESPECTIVOS CARGOS
-- 6.5) CADASTRAR MAIS 2 FUNCIONÁRIOS SEM OS SEUS CARGOS
-- 7) TREINAR E TESTAR O JOIN (LEFT, RIGHT E JOIN)

-- DESAFIO
-- CRIAR UMA TERCEIRA TABELA PRA FAZER O JOIN COM 3 TABELAS
-- TESTAR O SUM E O GROUP